### PR TITLE
feat: add support for linux-arm64 platform

### PR DESCRIPTION
**Pull request by leoli0605**

### CODE REVIEW

**Comment by carlosperate** [comment]
Thanks for the PR @leoli0605!
Have you tried this with a custom runner on an Linux Arm platform? If so, could you link the job output here to check it out? I don't have any around to test this at the moment.

**Comment by leoli0605** [comment]
> Thanks for the PR @leoli0605! Have you tried this with a custom runner on an Linux Arm platform? If so, could you link the job output here to check it out? I don't have any around to test this at the moment.

Hi @carlosperate, sorry for the late reply. I've updated the function that determines whether a Linux architecture is x86_64 or arm64. Fixed the incorrect MD5 checksum and download URL for arm64, and added some conditions to test.yml to ensure every test will pass when the architecture is arm64.

[Here](https://github.com/leoli0605/arm-none-eabi-gcc-action/actions/runs/7756530750)'s the test workflow within Linux arm64 architecture; please check it.

If there are any questions, please let me know. Thank you.

**Comment by leoli0605** [comment]
Hi @carlosperate, could you please take the time to review this PR when you have a moment? Thank you.

**Comment by carlosperate** [comment]
Sorry it's taken me this long to review this PR, I've been meaning to set up a Raspberry Pi to be able to test this regularly in CI, but didn't really  get around to it until now.

I've run an initial test and it looks like this is picking up the `linux_x86_64` build instead of `linux_aarch64`, like in here:
https://github.com/carlosperate/arm-none-eabi-gcc-action/actions/runs/9909692414/job/27378355053

Unfurtunately I cannot check the log from you CI run as it's been too long, do you remember checking which gcc version it was downloading? If you could push an empty commit to trigger another CI run on your fork it'd be useful to be able to compare the logs.

**Comment by carlosperate** [comment]
Ah, sorry I forgot you mentioned this and I didn't rebuild/package:

> BTW, for this PR, I did not update the `dist` result. If you approve this PR, please update the `dist` result. Thanks.

It seems to be working now, but will take a little while for all the jobs to run through the single Pi for linux arm64.
https://github.com/carlosperate/arm-none-eabi-gcc-action/actions/runs/9910086577/job/27379690774

**Review by carlosperate — APPROVED** [review]
Thanks for the PR adding Linux arm64 support, it's really appreciated!

**Pull request merged**
